$(document).ready(function(){wow=new WOW({animateClass:'animated',offset:100,mobile:!0,live:!0,callback:function(box){console.log("WOW: animating <"+box.tagName.toLowerCase()+">")}});wow.init();$('.slider-down a[href*="#"]').not('[href="#"]').not('[href="#0"]').click(function(event){if(location.pathname.replace(/^\//,'')==this.pathname.replace(/^\//,'')&&location.hostname==this.hostname){var target=$(this.hash);target=target.length?target:$('[name='+this.hash.slice(1)+']');if(target.length){event.preventDefault();$('html, body').animate({scrollTop:target.offset().top-$('.navigation-bar').outerHeight(!0)},1000)}}});$(window).bind('scroll',function(){var navHeight=120;($(window).scrollTop()>navHeight)?$('.navigation-bar').addClass('sticky'):$('.navigation-bar').removeClass('sticky')})
$('#file-upload').change(function(){var file=$('#file-upload')[0].files[0].name;$('label.custom-file-upload').text(file)})});$(document).ready(function(){$('.footer-heading').click(function(){var windiwWidth=$(window).width();if(windiwWidth<767){$(this).next('.footer-cont').slideToggle();$(this).find('.linkToggle').toggleClass('open')}})});$(document).ready(function(){$('[data-fancybox="images"]').fancybox({afterLoad:function(instance,current){var pixelRatio=window.devicePixelRatio||1;if(pixelRatio>1.5){current.width=current.width/pixelRatio;current.height=current.height/pixelRatio}}});$('[data-fancybox]').fancybox({youtube:{controls:1,showinfo:0},vimeo:{color:'f00'}})});$('.tranding-blocks .autoplay').slick({slidesToShow:3,slidesToScroll:1,autoplay:!0,autoplaySpeed:2000,arrows:!0,prevArrow:'<button class="button-pre"></button>',nextArrow:'<button class="button-next"></button>',responsive:[{breakpoint:992,settings:{slidesToShow:2,slidesToScroll:1,infinite:!0}},{breakpoint:641,settings:{slidesToShow:1,slidesToScroll:1,infinite:!0}}]});var rev=$('.rev_slider');rev.on('init',function(event,slick,currentSlide){var
cur=$(slick.$slides[slick.currentSlide]),next=cur.next(),prev=cur.prev();prev.addClass('slick-sprev');next.addClass('slick-snext');cur.removeClass('slick-snext').removeClass('slick-sprev');slick.$prev=prev;slick.$next=next}).on('beforeChange',function(event,slick,currentSlide,nextSlide){console.log('beforeChange');var cur=$(slick.$slides[nextSlide]);console.log(slick.$prev,slick.$next);slick.$prev.removeClass('slick-sprev');slick.$next.removeClass('slick-snext');next=cur.next(),prev=cur.prev();prev.prev();prev.next();prev.addClass('slick-sprev');next.addClass('slick-snext');slick.$prev=prev;slick.$next=next;cur.removeClass('slick-next').removeClass('slick-sprev')});rev.slick({speed:1000,arrows:!0,dots:!1,focusOnSelect:!0,prevArrow:'<button class="button-pre"></button>',nextArrow:'<button class="button-next"></button>',infinite:!0,centerMode:!0,slidesPerRow:1,slidesToShow:1,slidesToScroll:1,centerPadding:'0',swipe:!0,customPaging:function(slider,i){return''},});$('.therapislickslider').slick({dots:!0,arrows:!1,infinite:!0,autoplay:!0,speed:300,slidesToShow:3,slidesToScroll:1,responsive:[{breakpoint:992,settings:{slidesToShow:2,slidesToScroll:1,infinite:!0}},{breakpoint:641,settings:{slidesToShow:1,slidesToScroll:1,infinite:!0}}]});(function($){$(window).resize(function(){$(".full-slider").css("height",$(window).height())});$(document).ready(function(){$(".full-slider").css("height",$(window).height())});$('.full-slider .carousel').carousel({interval:5000,pause:"false",swipe:30});$(document).ready(function(){$('.single-item').slick({dots:!1,infinite:!0,speed:500,slidesToShow:1,slidesToScroll:1,prevArrow:'<button class="button-pre"> <i class="fa fa-long-arrow-left"></i></button>',nextArrow:'<button class="button-next"> <i class="fa fa-long-arrow-right"></i></button>',responsive:[{breakpoint:992,settings:{slidesToShow:1,slidesToScroll:1,infinite:!0}}]})});$(window).load(function(){$('.gridlayout').isotope({itemSelector:'.grid-item',masonry:{columnWidth:'.grid-item'}})})})(jQuery);$(document).ready(function(){$(".tab-years .block-nav-tabs > li > a").click(function(){$(this).tab('show')})});$(document).ready(function(){$(".tab-country .block-nav-tabs > li > a").click(function(){$(this).tab('show')})});$(document).ready(function(){$('.sidetop-overlay').slideUp('slow');$("#toggle-right").click(function(e){e.stopPropagation();$(".sidetop-overlay").slideToggle('slow')})});$(document).click(function(){$('.sidetop-overlay').slideUp('slow')});$('.sidetop-overlay').click(function(e){e.stopPropagation()});$('.resp-panel').click(function(e){var topoffset=0;$('html, body').animate({scrollTop:$(".resp-pgroup").offset().top-100},1200,'easeInOutExpo')});$(".menu-item-has-children a").click(function(event){if($(this).siblings(".sub-menu").length){event.preventDefault();$(this).siblings(".sub-menu").toggleClass("toggled-on");$(this).parent('.menu-item-has-children').toggleClass("toggled-on");$(this).siblings("button.dropdown-toggle").toggleClass("toggled-on")}})
jQuery(document).scroll(function() {
	var y = jQuery(this).scrollTop(); 
	if (y > 300) {
		if(!localStorage.showPolicyBlockFooter){
			console.log(localStorage.showPolicyBlockFooter);
			jQuery('.show-policy-block').fadeIn(); 
			jQuery(".policy-block").removeClass("show-policy-block"); 
		}
		//jQuery('.show-policy-block').fadeIn(); 
		//jQuery(".policy-block").removeClass("show-policy-block"); 	
		
	} 
}); 
jQuery('.hide-policy-block').click(function(e){
	e.preventDefault();
	document.cookie = "showPolicyBlockFooter=no";
	localStorage.setItem("showPolicyBlockFooter", true);
	console.log(document.cookie);
	jQuery('.policy-block').fadeOut();
});